name: markethink
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.24

environment:
  sdk: ^3.5.3

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  cloud_firestore: ^5.4.4
  cupertino_icons: ^1.0.8
  easy_stepper: ^0.8.5+1
  firebase_admin: ^0.3.0
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_ui_auth: ^1.16.0
  flutter:
    sdk: flutter
  flutter_floating_bottom_bar: ^1.2.1+1
  flutter_form_builder: ^9.4.1
  form_builder_file_picker: ^4.2.0
  form_builder_validators: ^11.0.0
  go_router: ^14.3.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  loading_animation_widget: ^1.3.0
  multi_dropdown: ^3.0.1
  sqflite: ^2.4.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets: 
    - assets/kotaKab.json
    - assets/personel.json

