name: markethink
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  easy_stepper: ^0.8.5+1
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.4.1
  flutter_osm_plugin: ^1.3.4
  google_fonts: ^6.2.1
  intl: ^0.19.0
  multi_dropdown: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
