// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgB5QldJd3rkPqmsVZ8tTBPMCBaqQpKLo',
    appId: '1:267505524494:web:1414d9f312c55b5f9d815f',
    messagingSenderId: '267505524494',
    projectId: 'markethink-59488',
    authDomain: 'markethink-59488.firebaseapp.com',
    storageBucket: 'markethink-59488.appspot.com',
    measurementId: 'G-S9Y1RP5LHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm_zYn5D2Ccmhj_Vv0Y1RDXEKPgmjyF8s',
    appId: '1:267505524494:android:c763f1de77fb05e49d815f',
    messagingSenderId: '267505524494',
    projectId: 'markethink-59488',
    storageBucket: 'markethink-59488.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgLHc6Q2U0tY7jeIeBilhzRNFoa-GdUuM',
    appId: '1:267505524494:ios:79b96efa71e172b19d815f',
    messagingSenderId: '267505524494',
    projectId: 'markethink-59488',
    storageBucket: 'markethink-59488.appspot.com',
    iosBundleId: 'com.example.markethink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgLHc6Q2U0tY7jeIeBilhzRNFoa-GdUuM',
    appId: '1:267505524494:ios:79b96efa71e172b19d815f',
    messagingSenderId: '267505524494',
    projectId: 'markethink-59488',
    storageBucket: 'markethink-59488.appspot.com',
    iosBundleId: 'com.example.markethink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgB5QldJd3rkPqmsVZ8tTBPMCBaqQpKLo',
    appId: '1:267505524494:web:d592e49f1c2d37a89d815f',
    messagingSenderId: '267505524494',
    projectId: 'markethink-59488',
    authDomain: 'markethink-59488.firebaseapp.com',
    storageBucket: 'markethink-59488.appspot.com',
    measurementId: 'G-B4CRNYMLL2',
  );

}